import type { Metadata } from "next";
import { absoluteUrl } from "@/lib/site-config";

export const metadata: Metadata = {
  title: "Terms & Conditions — Kraviona Tools",
  description: "Terms and conditions for using Kraviona Tools. Free browser-based tools for SEO, content, and digital marketing.",
  alternates: { canonical: absoluteUrl("/terms") },
};

export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-14">
      <h1 className="text-2xl sm:text-3xl font-bold text-gray-900 mb-2">Terms & Conditions</h1>
      <p className="text-sm text-gray-400 mb-8">Last updated: {new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}</p>

      <div className="prose">
        <p className="text-gray-600 mb-6 leading-relaxed">
          By using Kraviona Tools, you agree to these terms. Please read them carefully.
        </p>

        <h2>1. Use of Tools</h2>
        <p>
          All tools on Kraviona are provided for lawful purposes only. You agree not to use the tools to process illegal content, infringe intellectual property, or engage in any activity that violates applicable law.
        </p>

        <h2>2. No Warranties</h2>
        <p>
          Kraviona Tools is provided &quot;as is&quot; without warranties of any kind. We do not guarantee that the tools will be error-free, uninterrupted, or produce results suitable for any specific purpose. Use tools at your own discretion and always verify important outputs.
        </p>

        <h2>3. Limitation of Liability</h2>
        <p>
          Kraviona Tools and its operators are not liable for any direct, indirect, incidental, or consequential damages arising from your use of the tools, including but not limited to data loss, file corruption, or inaccurate results.
        </p>

        <h2>4. Intellectual Property</h2>
        <p>
          The Kraviona Tools platform, design, and code are the intellectual property of Kraviona Tools. You may not reproduce, duplicate, or resell the platform without written permission. Tool outputs generated by your inputs belong to you.
        </p>

        <h2>5. Changes to Terms</h2>
        <p>
          We reserve the right to modify these terms at any time. Continued use of the platform after changes constitutes acceptance of the updated terms.
        </p>

        <h2>6. Contact</h2>
        <p>
          For questions about these terms, contact{" "}
          <a href="mailto:hello@kraviona.site" className="text-purple-600 hover:underline">hello@kraviona.site</a>.
        </p>
      </div>
    </div>
  );
}
